# Generated by Django 5.1.7 on 2025-03-22 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counterpartys',
            options={'verbose_name': 'Контрагент', 'verbose_name_plural': 'Контрагенты'},
        ),
    ]
