# Generated by Django 5.1.7 on 2025-03-24 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0002_alter_counterpartys_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Counterpartys',
            new_name='Counterparties',
        ),
    ]
