# Generated by Django 5.1.8 on 2025-04-20 18:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counterparties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер ордера')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата ордера')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('basis', models.TextField(verbose_name='Основание')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Утвержден'), ('executed', 'Исполнен'), ('canceled', 'Отменен')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_expense_orders', to=settings.AUTH_USER_MODEL, verbose_name='Кем утвержден')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_expense_orders', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counterparties.counterparties', verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Расходный кассовый ордер',
                'verbose_name_plural': 'Расходные кассовые ордера',
                'ordering': ['-date', '-number'],
            },
        ),
    ]
