# Generated by Django 5.1.7 on 2025-03-25 17:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Номер ордера')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата ордера')),
                ('recipient', models.CharField(max_length=255, verbose_name='Получатель')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма')),
                ('purpose', models.TextField(verbose_name='Назначение платежа')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Утвержден'), ('executed', 'Исполнен'), ('cancelled', 'Отменен')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_expense_orders', to=settings.AUTH_USER_MODEL, verbose_name='Утвердил')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_expense_orders', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Расходный кассовый ордер',
                'verbose_name_plural': 'Расходные кассовые ордера',
                'ordering': ['-order_date', '-created_at'],
            },
        ),
    ]
