# Generated by Django 5.1.7 on 2025-03-25 19:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenseorder',
            options={'ordering': ['-date', '-number'], 'verbose_name': 'Расходный кассовый ордер', 'verbose_name_plural': 'Расходные кассовые ордера'},
        ),
        migrations.RenameField(
            model_name='expenseorder',
            old_name='order_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='expenseorder',
            name='purpose',
        ),
        migrations.AddField(
            model_name='expenseorder',
            name='basis',
            field=models.TextField(default=1, verbose_name='Основание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenseorder',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='expenseorder',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='expenseorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_expense_orders', to=settings.AUTH_USER_MODEL, verbose_name='Кем утвержден'),
        ),
        migrations.AlterField(
            model_name='expenseorder',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_expense_orders', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан'),
        ),
        migrations.AlterField(
            model_name='expenseorder',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Номер ордера'),
        ),
        migrations.AlterField(
            model_name='expenseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Утвержден'), ('executed', 'Исполнен'), ('canceled', 'Отменен')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
