# Generated by Django 5.1.7 on 2025-03-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_orders', '0003_alter_expenseorder_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseorder',
            name='recipient',
            field=models.CharField(max_length=255, verbose_name='Получатель'),
        ),
    ]
