# Generated by Django 5.1.7 on 2025-03-28 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_orders', '0004_alter_expenseorder_recipient'),
        ('counterparties', '0003_rename_counterpartys_counterparties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseorder',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='counterparties.counterparties', verbose_name='Получатель'),
        ),
    ]
