# Generated by Django 5.2 on 2025-04-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_orders', '0006_alter_expenseorder_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseorder',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата ордера'),
        ),
    ]
