# Generated by Django 5.2 on 2025-04-15 10:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_orders', '0007_alter_expenseorder_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseorder',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата ордера'),
        ),
    ]
