# Generated by Django 5.1.7 on 2025-04-04 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='OrderTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата и время')),
                ('status', models.CharField(choices=[('paid', 'Оплачено'), ('unpaid', 'Неоплачено'), ('canceled', 'Отменено')], default='unpaid', max_length=10, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Стол заказов',
                'verbose_name_plural': 'Столы заказов',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Стол', max_length=100, verbose_name='Стол')),
            ],
            options={
                'verbose_name': 'Стол',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Цена')),
                ('sum', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Сумма')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.ordertable', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Элемент заказа',
                'verbose_name_plural': 'Элементы заказа',
            },
        ),
        migrations.CreateModel(
            name='CashReceiptOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('sum', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Сумма')),
                ('order', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='cashoeceiptorder_table', to='directory.ordertable', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Приходный кассовый ордер',
                'verbose_name_plural': 'Приходные кассовые ордера',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименования')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.category', verbose_name='Категория')),
                ('type', models.ForeignKey(default='шт', on_delete=django.db.models.deletion.PROTECT, to='directory.type', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.AddField(
            model_name='ordertable',
            name='products',
            field=models.ManyToManyField(through='directory.OrderItem', to='directory.products', verbose_name='Товары'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.products', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='ordertable',
            name='table',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='directory.table'),
        ),
    ]
