# Generated by Django 5.1.7 on 2025-04-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordertable',
            options={},
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='products',
            field=models.ManyToManyField(through='directory.OrderItem', to='directory.products'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='status',
            field=models.CharField(choices=[('paid', 'Оплачено'), ('unpaid', 'Неоплачено'), ('canceled', 'Отменено')], default='unpaid', max_length=10),
        ),
    ]
