# Generated by Django 5.1.7 on 2025-03-09 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('table', models.CharField(default='Стол', max_length=50, verbose_name='Стол')),
                ('count', models.IntegerField(verbose_name='Коли́чество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('sum', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Сумма')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.products', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Стол заказов',
            },
        ),
    ]
