# Generated by Django 5.1.7 on 2025-03-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_ordertable'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='status',
            field=models.CharField(choices=[('paid', 'Оплачено'), ('unpaid', 'Неоплачено'), ('canceled', 'Отменено')], default='unpaid', max_length=10, verbose_name='Статус'),
        ),
    ]
