# Generated by Django 5.1.7 on 2025-04-04 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_alter_ordertable_options_alter_ordertable_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashreceiptorder',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cashreceiptorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_orders', to='directory.ordertable'),
        ),
        migrations.AlterField(
            model_name='cashreceiptorder',
            name='sum',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
