# Generated by Django 5.1.7 on 2025-04-04 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_alter_cashreceiptorder_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertable',
            name='products',
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.table'),
        ),
    ]
