# Generated by Django 5.1.7 on 2025-03-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_ordertable_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='status',
            field=models.CharField(choices=[('paid', 'Оплачено'), ('unpaid', 'Не оплачено'), ('canceled', 'Отменено')], default='unpaid', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
