# Generated by Django 5.1.7 on 2025-04-04 20:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_remove_ordertable_products_alter_ordertable_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
