# Generated by Django 5.1.7 on 2025-03-19 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_alter_ordertable_options_remove_ordertable_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Стол')),
            ],
            options={
                'verbose_name': 'Стол',
                'verbose_name_plural': 'Столы',
            },
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.table', verbose_name=' Стол'),
        ),
    ]
