# Generated by Django 5.1.7 on 2025-03-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_table_alter_ordertable_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='table',
            field=models.CharField(default='Стол', max_length=50, verbose_name='Стол'),
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
