# Generated by Django 5.1.7 on 2025-03-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_table_alter_ordertable_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата и время'),
        ),
    ]
