# Generated by Django 5.1.7 on 2025-03-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_cashregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
