# Generated by Django 5.1.7 on 2025-03-22 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0011_alter_cashregister_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashregister',
            options={},
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashregister_order', to='directory.ordertable', verbose_name='Заказ'),
        ),
    ]
