# Generated by Django 5.1.7 on 2025-03-22 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0012_alter_cashregister_options_alter_cashregister_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='order',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='cashregister_order', to='directory.ordertable', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='sum',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
