# Generated by Django 5.1.7 on 2025-03-22 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0013_alter_cashregister_date_alter_cashregister_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='sum',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='directory.orderitem'),
        ),
    ]
