# Generated by Django 5.1.7 on 2025-03-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0014_alter_cashregister_sum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashregister',
            options={'verbose_name': 'Приходный кассовый ордер', 'verbose_name_plural': 'Приходные кассовые ордера'},
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='sum',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Сумма'),
        ),
    ]
