# Generated by Django 5.1.7 on 2025-03-22 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0015_alter_cashregister_options_alter_cashregister_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='order',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='cashregister_table', to='directory.ordertable', verbose_name='Заказ'),
        ),
    ]
