# Generated by Django 5.1.7 on 2025-03-25 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0016_alter_cashregister_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashReceiptOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('sum', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Сумма')),
                ('order', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='cashoeceiptorder_table', to='directory.ordertable', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Приходный кассовый ордер',
                'verbose_name_plural': 'Приходные кассовые ордера',
            },
        ),
        migrations.DeleteModel(
            name='CashRegister',
        ),
    ]
