# Generated by Django 5.1.8 on 2025-06-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.CharField(choices=[('legal', 'Юрид/лицо'), ('IP', 'ИП')], default='legal', max_length=25, verbose_name='вид')),
                ('inn', models.IntegerField(blank=True, unique=True, verbose_name='ИНН')),
                ('kPP', models.IntegerField(blank=True, verbose_name='КПП')),
                ('Address', models.CharField(blank=True, max_length=150, verbose_name='Адрес')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='mail')),
                ('director', models.CharField(blank=True, max_length=50, verbose_name='ФИО')),
            ],
        ),
    ]
