# Generated by Django 5.1.7 on 2025-03-22 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counterparties', '0002_alter_counterpartys_options'),
        ('directory', '0009_alter_ordertable_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionsProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('count', models.FloatField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Цена')),
                ('sum', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='counterparties.counterpartys', verbose_name='Контрагент')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.products', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Поступление',
            },
        ),
    ]
