# Generated by Django 5.1.7 on 2025-03-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_alter_admissionsproducts_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionsproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
    ]
