# Generated by Django 5.1.7 on 2025-03-22 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_cashregister'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CashRegister',
        ),
    ]
